CREATE TABLE COMMENTS(
    COMMENT_NO NUMBER(8) NOT NULL, -- PK
    DIARY_NO NUMBER(6) NOT NULL, -- FK
    COMMENT_CONTENT VARCHAR2(30 CHAR) NOT NULL,
    COMMENT_WRITING_TIME DATE NOT NULL,
    CONSTRAINT COMMENTS_PK PRIMARY KEY(COMMENT_NO, DIARY_NO),
    CONSTRAINT COMMENTS_TRAVELS_FK FOREIGN KEY(DIARY_NO) REFERENCES TRAVELS(DIARY_NO)
);

INSERT INTO COMMENTS VALUES(1, 1, '샘플데이터어', TO_DATE('20200622 121011', 'yyy-mm-dd hh24:mi:ss'));
INSERT INTO COMMENTS VALUES(1, 2, '샘플데이터어', TO_DATE('20200624 121011', 'yyy-mm-dd hh24:mi:ss')); -- 댓글 내용 중복
INSERT INTO COMMENTS VALUES(1, 3, '샘플데이터어어', TO_DATE('20200622 121011', 'yyy-mm-dd hh24:mi:ss')); -- 글 작성 일자보다 일찍 댓글
INSERT INTO COMMENTS VALUES(1, 1, '샘플데이터어어어', TO_DATE('20200622 121013', 'yyy-mm-dd hh24:mi:ss')); -- PK 중복
