CREATE TABLE HASHTAGS(
    DIARY_NO NUMBER(6) NOT NULL,
    DIARY_TAG VARCHAR2(5 CHAR) NOT NULL,
    CONSTRAINT HASHTAGS_PK PRIMARY KEY(DIARY_NO, DIARY_TAG),
    CONSTRAINT HASHTAGS_TRAVELS_FK1 FOREIGN KEY(DIARY_NO) REFERENCES TRAVELS(DIARY_NO),
    CONSTRAINT HASHTAGS_TRAVELS_FK2 FOREIGN KEY(DIARY_TAG) REFERENCES TRAVELS(DIARY_TAG)
);
