CREATE TABLE LIKES(
    DIARY_NO NUMBER(6), -- FK, PK
    ID VARCHAR2(20 CHAR), -- FK , PK
    CONSTRAINT LIKES_PK PRIMARY KEY(DIARY_NO,ID),
    CONSTRAINT LIKES_CLIENTS_FK FOREIGN KEY(ID) REFERENCES CLIENTS(ID),
    CONSTRAINT LIKES_TRAVELS_FK FOREIGN KEY(DIARY_NO) REFERENCES TRAVELS(DIARY_NO)
);

INSERT INTO LIKES VALUES(1, 'koreaman@gmail.com');
INSERT INTO LIKES VALUES(2, 'japanman@gmail.com'); 
INSERT INTO LIKES VALUES(3, 'chinaman@gmail.com');
INSERT INTO LIKES VALUES(4, 'americaman@gmail.com'); -- PK LIKE_NO 중복
INSERT INTO LIKES VALUES(222, 'koreaman@gmail.com'); -- PK LIKE_ID 중복
