CREATE TABLE REGIONS(
    REGION_NO NUMBER NOT NULL, -- PK
    REGION_NAME VARCHAR2(8 CHAR) NOT NULL,
    CONSTRAINT REGIONS_PK PRIMARY KEY(REGION_NO)
);
-- 실제 데이터 예정
INSERT   INTO VALUES REGIONS(1, '서울');
INSERT   INTO VALUES REGIONS(2, '부산');
INSERT   INTO VALUES REGIONS(3, '대구');
INSERT   INTO VALUES REGIONS(4, '인천');
INSERT   INTO VALUES REGIONS(5, '광주');
INSERT   INTO VALUES REGIONS(6, '대전');
INSERT   INTO VALUES REGIONS(7, '울산');
INSERT   INTO VALUES REGIONS(8, '세종특별자치시');
INSERT   INTO VALUES REGIONS(9, '경기');
INSERT   INTO VALUES REGIONS(10, '충북');
INSERT   INTO VALUES REGIONS(11, '충남');
INSERT   INTO VALUES REGIONS(12, '전북');
INSERT   INTO VALUES REGIONS(13, '전남');
INSERT   INTO VALUES REGIONS(14, '경남');
INSERT   INTO VALUES REGIONS(15, '경북');
INSERT   INTO VALUES REGIONS(16, '제주특별자치도');